### ISSUE TITLE
Wireframe CSS mockups for having a clean  and uniform design in the app

### ISSUE THREAD

**Issue by twentymurial33** [twentymurial33/murials_menu#109]
![Screen Shot 2023-04-18 at 1 15 33 PM](https://user-images.githubusercontent.com/34128735/233390226-bc49177d-4615-4a3d-8481-3a1657887c26.png)
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/34128735/233785064-aecbefec-476a-4648-8394-612cc8ae4db5.png">

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/34128735/233786367-af12c756-f41d-43e7-9d5f-e8635748b60c.png">

**Comment by brentmclark** [comment]
![image](https://user-images.githubusercontent.com/316743/234724079-f8c2114f-ec91-4050-87a0-0072f904b327.png)

**Comment by brentmclark** [comment]
![image](https://user-images.githubusercontent.com/316743/234724613-47a30f5a-d363-47cd-8349-86c7359dc493.png)

**Comment by brentmclark** [comment]
![image](https://user-images.githubusercontent.com/316743/234725679-7d48b6d0-7f3e-48bf-afd0-5c1186ee6b33.png)
