### ISSUE TITLE
Create Records on Prisma - Update records to "menu_Items"

### ISSUE THREAD

**Issue by twentymurial33** [twentymurial33/murials_menu#17]
Use our ORM `Prisma` to create different records. @brentmclark I have been playing around with Prisma Studio and its very cool

**Comment by twentymurial33** [comment]
💯  created my 1st record on `Prisma` ...falling in love with it

**Comment by brentmclark** [comment]
![Shaq Shimmy GIF](https://c.tenor.com/aSW9ZfIIC64AAAAM/shaq-shimmy.gif)

**Comment by brentmclark** [comment]
That's how it starts!

**Comment by twentymurial33** [comment]
https://github.com/twentymurial33/murials_menu/pull/19
