### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by twentymurial33** [twentymurial33/murials_menu#4]
Implement search functionality that will enable users to search menu items. Search by food name.

**Comment by twentymurial33** [comment]
Adding search button to map over fetched objects - currently button is displaying however when I add more items to mockable IO I don't see them in the API

**Comment by brentmclark** [comment]
Hmmmmm.  Are you refreshing the page after adding the items to mockable?  React-query will cache previous fetch results.

**Comment by twentymurial33** [comment]
Pending PR review
