### ISSUE TITLE
Update and Maintain `Package.json`

### ISSUE THREAD

**Issue by twentymurial33** [twentymurial33/murials_menu#62]
Package.json needs to be updated and maintained as the project grows

**Comment by brentmclark** [comment]
The root level package.json file has hundred of dependencies in it.  That is uncommon, especially for a project of this size.  I recommend running `npx depcheck` to detect unused dependencies and then remove anything you don't need.  This will speed up the build time and reduce the surface area for bugs.

**Comment by twentymurial33** [comment]
Ran `npx depcheck` and received a list of dependencies currently not in use 
<img width="442" alt="Screen Shot 2022-12-07 at 9 00 54 AM" src="https://user-images.githubusercontent.com/34128735/206205101-a377e605-c3bb-4e4e-981c-f10e9bc736cf.png">
