### ISSUE TITLE
Consider the after-edit UX of the edit page

### ISSUE THREAD

**Issue by brentmclark** [twentymurial33/murials_menu#76]
Should customers stay on that page, or be routed back to the listing page?

**Comment by twentymurial33** [comment]
Currently the user has the ability to edit the item and then click on the `details` page button to be routed back to the listings, is there a design flow I should be exploring further than this? @brentmclark

**Comment by brentmclark** [comment]
I think it's the `Details Page` button that's tripping me up.  `Update Item` is a standard call-to-action.  There's a verb and a noun.  I have a reasonable understanding of what is going to happen when I click that button.  

`Details Page` is only a noun, no verb.  And it doesn't take me to a details page, it takes me to a listing page.  This leaves me extra confused about what will happen when I click that button.  So much so that I forget what it does every time I see it.

How do you feel about changing the text on that button to something like `Back to the Menu` or `View All Menu Items`?  That might be all that is needed here to close the UX gap I'm experiencing.

**Comment by twentymurial33** [comment]
Thank you - I have gone with renaming the button to `Back to Menu`
