### ISSUE TITLE
Add and use fetch-mock in tests

### ISSUE THREAD

**Issue by brentmclark** [twentymurial33/murials_menu#77]
Instead of hitting a live API endpoint in your tests for `queryAPI` you should consider using an API mock such as `fetch-mock`.  This will allow to you simulate API calls with 200 and non-200 responses without using bogus URLs or having to keep your node server running.

https://github.com/twentymurial33/murials_menu/pull/78 - Current PR

**Comment by twentymurial33** [comment]
https://github.com/twentymurial33/murials_menu/pull/78 - Current PR
